from PyQt5 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.groupBox0 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox0.setGeometry(QtCore.QRect(30, 250, 251, 331))
        self.groupBox0.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox0.setFlat(False)
        self.groupBox0.setCheckable(False)
        self.groupBox0.setObjectName("groupBox0")
        
        self.pushButton0_1 = QtWidgets.QPushButton(self.groupBox0)
        self.pushButton0_1.setGeometry(QtCore.QRect(50, 40, 131, 71))
        self.pushButton0_1.setObjectName("pushButton0_1")
        self.pushButton0_2 = QtWidgets.QPushButton(self.groupBox0)
        self.pushButton0_2.setGeometry(QtCore.QRect(50, 130, 131, 71))
        self.pushButton0_2.setObjectName("pushButton0_2")
        self.pushButton0_3 = QtWidgets.QPushButton(self.groupBox0)
        self.pushButton0_3.setGeometry(QtCore.QRect(50, 220, 131, 71))
        self.pushButton0_3.setObjectName("pushButton0_3")
        
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(310, 30, 251, 511))
        self.groupBox1.setObjectName("groupBox1")
        self.pushButton1_1 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1_1.setGeometry(QtCore.QRect(60, 30, 121, 61))
        self.pushButton1_1.setObjectName("pushButton1_1")
        self.pushButton1_2 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1_2.setGeometry(QtCore.QRect(60, 100, 121, 61))
        self.pushButton1_2.setObjectName("pushButton1_2")
        
        self.groupBox1_1 = QtWidgets.QGroupBox(self.groupBox1)
        self.groupBox1_1.setGeometry(QtCore.QRect(30, 170, 181, 161))
        self.groupBox1_1.setObjectName("groupBox1_1")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox1_1)
        self.spinBox.setGeometry(QtCore.QRect(60, 30, 61, 41))
        self.spinBox.setObjectName("spinBox")
        self.pushButton1_3 = QtWidgets.QPushButton(self.groupBox1_1)
        self.pushButton1_3.setGeometry(QtCore.QRect(30, 80, 121, 61))
        self.pushButton1_3.setObjectName("pushButton1_3")
        
        self.pushButton1_4 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1_4.setGeometry(QtCore.QRect(60, 340, 121, 61))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.pushButton1_5 = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton1_5.setGeometry(QtCore.QRect(60, 410, 121, 61))
        self.pushButton1_5.setObjectName("pushButton1_5")
        
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 30, 231, 301))
        self.groupBox.setObjectName("groupBox")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setGeometry(QtCore.QRect(30, 50, 161, 71))
        self.textEdit.setObjectName("textEdit")
        self.pushButton2_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton2_1.setGeometry(QtCore.QRect(20, 140, 181, 51))
        self.pushButton2_1.setObjectName("pushButton2_1")
        self.pushButton2_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton2_2.setGeometry(QtCore.QRect(20, 210, 181, 51))
        self.pushButton2_2.setObjectName("pushButton2_2")
        
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(310, 560, 251, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton3_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton3_1.setGeometry(QtCore.QRect(20, 70, 221, 81))
        self.pushButton3_1.setObjectName("pushButton3_1")
        
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 380, 321, 421))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton4_1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_1.setGeometry(QtCore.QRect(50, 30, 211, 61))
        self.pushButton4_1.setObjectName("pushButton4_1")
        self.pushButton4_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_2.setGeometry(QtCore.QRect(50, 110, 211, 61))
        self.pushButton4_2.setObjectName("pushButton4_2")
        self.pushButton4_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_3.setGeometry(QtCore.QRect(50, 190, 211, 61))
        self.pushButton4_3.setObjectName("pushButton4_3")
        self.pushButton4_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4_4.setGeometry(QtCore.QRect(50, 270, 211, 61))
        self.pushButton4_4.setObjectName("pushButton4_4")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox0.setTitle(_translate("MainWindow", "Load Image"))
        self.pushButton0_1.setText(_translate("MainWindow", "Load folder"))
        self.pushButton0_2.setText(_translate("MainWindow", "Load Image_L"))
        self.pushButton0_3.setText(_translate("MainWindow", "Load Image_R"))
        self.groupBox1.setTitle(_translate("MainWindow", "1. Calibration"))
        self.pushButton1_1.setText(_translate("MainWindow", "1.1 Find corners"))
        self.pushButton1_2.setText(_translate("MainWindow", "1.2 Find intrinsic"))
        self.groupBox1_1.setTitle(_translate("MainWindow", "1.3 Find extrinsic"))
        self.pushButton1_3.setText(_translate("MainWindow", "1.3 Find extrinsic"))
        self.pushButton1_4.setText(_translate("MainWindow", "1.4 Find distortion"))
        self.pushButton1_5.setText(_translate("MainWindow", "1.5 Show result"))
        self.groupBox.setTitle(_translate("MainWindow", "2. Augmented Reality"))
        self.pushButton2_1.setText(_translate("MainWindow", "2.1 Show words on board"))
        self.pushButton2_2.setText(_translate("MainWindow", "2.2 Show words vertical"))
        self.groupBox_2.setTitle(_translate("MainWindow", "3. Stereo Disparity Map"))
        self.pushButton3_1.setText(_translate("MainWindow", "3.1 Stereo Disparity Map"))
        self.groupBox_3.setTitle(_translate("MainWindow", "4. SIFT"))
        self.pushButton4_1.setText(_translate("MainWindow", "Load Image 1"))
        self.pushButton4_2.setText(_translate("MainWindow", "Load Image 2"))
        self.pushButton4_3.setText(_translate("MainWindow", "4.1 Keypoints"))
        self.pushButton4_4.setText(_translate("MainWindow", "4.2 Matched Keypoints"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
